# Generated by Django 4.2.19 on 2025-03-02 07:07

from django.db import migrations, models
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to=files.models.file_upload_path)),
                ("original_filename", models.CharField(db_index=True, max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image/png", "Image Png"),
                            ("image/jpeg", "Image Jpeg"),
                            ("image/gif", "Image Gif"),
                            ("application/pdf", "Application Pdf"),
                            ("text/plain", "Text Plain"),
                            ("text/csv", "Text Csv"),
                            ("image/bmp", "Image Bmp"),
                            ("image/tiff", "Image Tiff"),
                            ("image/webp", "Image Webp"),
                            ("audio/mpeg", "Audio Mpeg"),
                            ("audio/ogg", "Audio Ogg"),
                            ("audio/wav", "Audio Wav"),
                            ("video/mp4", "Video Mp4"),
                            ("video/x-msvideo", "Video Avi"),
                            ("video/webm", "Video Webm"),
                            ("application/zip", "Application Zip"),
                            ("application/gzip", "Application Gzip"),
                            ("application/json", "Application Json"),
                            ("application/xml", "Application Xml"),
                            ("application/msword", "Application Msword"),
                            ("application/vnd.ms-excel", "Application Vnd Ms Excel"),
                            (
                                "application/vnd.ms-powerpoint",
                                "Application Vnd Ms Powerpoint",
                            ),
                            (
                                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                                "Application Vnd Openxmlformats Officedocument Wordprocessingml Document",
                            ),
                            (
                                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                "Application Vnd Openxmlformats Officedocument Spreadsheetml Sheet",
                            ),
                            (
                                "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                                "Application Vnd Openxmlformats Officedocument Presentationml Presentation",
                            ),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                ("size", models.BigIntegerField(db_index=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("hash", models.CharField(default=None, max_length=64)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageSavings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=64, unique=True)),
                ("saved_size", models.BigIntegerField(default=0)),
                ("file_count", models.IntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
